version: "3.8"
services:
  arqmedes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arqmedes
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/arqmedes
      - ./docker/apache/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    container_name: mysql
    build: ./docker/mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arqmedes
      MYSQL_PASSWORD: root
    volumes:
      - "./docker/mysql/config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
      - "./docker/mysql/initdb:/docker-entrypoint-initdb.d"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
