<div class="row">
    <div class="col-12 d-flex justify-content-end align-items-center mb-5">
        <a class="btn btn-sm btn-success text-white" href="/produtos/cadastrar">Cadastrar Produto +</a>
    </div>
    <div class="col">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>SKU</th>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Quantidade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($produtos as $produto) : ?>
                <tr>
                    <td><?= $produto->sku; ?></td>
                    <td><?= $produto->name; ?></td>
                    <td>R$ <?= number_format($produto->price, 2, ',', '.'); ?></td>
                    <td><?= $produto->quantity; ?></td>
                    <td class="d-flex justify-content-around">
                        <a href="/produtos/detalhes/<?= $produto->id;?>">[Detalhes]</a> |
                        <a href="/produtos/editar/<?= $produto->id;?>">[Editar]</a> |
                        <a href="">[Excluir]</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>