<div class="row">
    <div class="col-12 d-flex justify-content-end align-items-center mb-5">
        <a class="btn btn-sm btn-success text-white" href="/produtos/cadastrar">Cadastrar Produto <i class="fa-solid fa-plus"></i></a>
    </div>
    <div class="col">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>SKU</th>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Quantidade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($produtos as $produto) : ?>
                <tr>
                    <td><?= $produto->sku; ?></td>
                    <td><?= $produto->name; ?></td>
                    <td>R$ <?= number_format($produto->price, 2, ',', '.'); ?></td>
                    <td><?= $produto->quantity; ?></td>
                    <td class="d-flex align-items-center text-center justify-content-around px-0">
                        <a class="btn btn-sm bg-info" role="button" href="/produtos/detalhes/<?= $produto->id;?>" title="Exibir Detalhes"><i class="fa-solid fa-eye"></i></a>
                        <a class="btn btn-sm bg-success" role="button" href="/produtos/editar/<?= $produto->id;?>" title="Editar Produto"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-sm bg-danger" role="button" href="/produtos/excluir/<?= $produto->id;?>" title="Excluir Produto"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>