<div class="row">
    <div class="col-12 d-flex justify-content-end align-items-end mb-5">
        <a class="btn btn-sm btn-success text-white" href="/produtos/cadastrar">Cadastrar Produto +</a>
    </div>
    <div class="col">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>SKU</th>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Quantidade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>JH61Sgs62</td>
                    <td>Veja</td>
                    <td>1.90</td>
                    <td>150</td>
                    <td class="d-flex justify-content-around">
                        <a href="">[Detalhes]</a> |
                        <a href="">[Editar]</a> |
                        <a href="">[Excluir]</a>
                    </td>
                </tr>
                <tr>
                    <td>GDHSG27s</td>
                    <td>Coca Cola</td>
                    <td>5.70</td>
                    <td>12</td>
                    <td class="d-flex justify-content-around">
                        <a href="">[Detalhes]</a> |
                        <a href="">[Editar]</a> |
                        <a href="">[Excluir]</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>