<!-- <?php

echo '<pre>' . print_r($product, true) . '</pre>';
?> -->

<div class="row">
    <div class="col-12 d-flex justify-content-start align-items-center mb-5">
        <a class="btn btn-sm btn-info text-white" href="/produtos"><- Voltar</a>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                Produto
            </div>
            <div class="card-body">
                <h4 class="card-title"><?= ucfirst($product->name); ?></h4>

                <div class="row">
                    <div class="col">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">SKU</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Preço</th>
                                    <th scope="col">Descrição</th>
                                    <th scope="col">Quantidade</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td scope="row"><?= $product->sku; ?></td>
                                    <td scope="row"><?= $product->name; ?></td>
                                    <td scope="row"><?= $product->price; ?></td>
                                    <td scope="row"><?= $product->description; ?></td>
                                    <td scope="row"><?= $product->quantity; ?></td>
                                </tr>
                                <tr class="px-0 mx-0">
                                    <td colspan="5">

                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                    <div class="col">
                        <div class="accordion mx-0 px-0" id="accordionExample">
                            <div class="card">
                                <div class="card-header bg-dark" id="headingOne">
                                    <h2 class="mb-0">
                                        <button class="btn btn-sm text-white" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Categorias
                                        </button>
                                    </h2>
                                </div>
                                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <ul class="list-group list-group-flush">
                                            <?php foreach ($product->categories as $category) : ?>
                                                <li class="list-group-item"><?= $category; ?></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>