<div id="notfound">
    <div class="notfound">
        <div class="notfound-404">
            <h1>404</h1>
        </div>
        <h2>Oops! Recurso não encontrado.</h2>
        <p>A página que você está procurando pode ter sido removida, seu nome alterado ou está temporariamente indisponível
        </p>
        <a class="btn btn-sm btn-primary" href="/"><i class="fa-solid fa-backward-step"></i> Voltar - Página inicial</a>
    </div>
</div>