<div class="row">
    <div class="col-12">
        <h2 class="text-center"><?= $action; ?> Produto</h2>
    </div>
    <div class="col mb-4">
        <a class="btn btn-sm btn-info px-2" href="/categorias"><i class="fa-solid fa-backward-step"></i> Cancelar</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <?php require VIEWS_MODULES_PATH . '/category/components/form-product.phtml'; ?>
    </div>
</div>