<div class="row">
    <div class="col-12 d-flex justify-content-end align-items-end mb-5">
        <a class="btn btn-sm btn-success text-white" href="/categorias/cadastrar">Cadastrar Categoria +</a>
    </div>
    <div class="col">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category) : ?>
                <tr>
                    <td><?= $category->id; ?></td>
                    <td><?= $category->name; ?></td>
                    <td class="d-flex justify-content-around">
                        <a href="">[Detalhes]</a> |
                        <a href="">[Editar]</a> |
                        <a href="">[Excluir]</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>