<div class="row">
    <div class="col-12 d-flex justify-content-end align-items-end mb-5">
        <a class="btn btn-sm btn-success text-white" href="/categorias/cadastrar">Cadastrar Categoria <i class="fa-solid fa-plus"></i></a>
    </div>
    <div class="col">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category) : ?>
                <tr>
                    <td><?= $category->id; ?></td>
                    <td><?= $category->name; ?></td>
                    <td class="d-flex align-items-center text-center justify-content-around px-0">
                        <a class="btn btn-sm bg-info" role="button" href="/categorias/detalhes/<?= $category->id;?>" title="Exibir Detalhes"><i class="fa-solid fa-eye"></i></a>
                        <a class="btn btn-sm bg-success" role="button" href="/categorias/editar/<?= $category->id;?>" title="Editar Categoria"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-sm bg-danger" role="button" href="/categorias/excluir/<?= $category->id;?>" title="Excluir Categoria"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>