<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
        <button
            class="navbar-toggler btn btn-dark d-inline-block d-lg-none ml-auto"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-2">
                <li class="nav-item <?= $this->activeController === 'home' ? 'active' : ''; ?>">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <?php if (\Arqmedes\Core\Session\Session::has('user')) : ?>
                    <li class="nav-item <?= $this->activeController === 'produtos' ? 'active' : ''; ?>">
                        <a class="nav-link" href="/produtos">Produtos</a>
                    </li>
                    <li class="nav-item <?= $this->activeController === 'categorias' ? 'active' : ''; ?>">
                        <a class="nav-link" href="/categorias">Categorias</a>
                    </li>
                <?php endif; ?>
            </ul>
            <ul class="nav navbar-nav ml-auto d-flex row justify-content-between ">
                <?php if (!\Arqmedes\Core\Session\Session::has('user')) : ?>
                    <li class="col-auto nav-item">
                        <a class="btn btn-sm btn-primary nav-link text-white" href="/auth/signin">Login</a>
                    </li>
                    <li class="col-auto nav-item">
                        <a class="btn btn-sm btn-success nav-link text-white" href="/auth/signup">Cadastre-se</a>
                    </li>
                <?php else: ?>
                    <li class="col-auto nav-item">
                        <a class="btn btn-sm btn-primary nav-link text-white" href="/auth/logout">Sair <i class="fa-solid fa-right-from-bracket"></i></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>