<nav id="sidebar">
    <div class="p-4 pt-5">
        <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(assets/images/logo.jpg);"></a>
        <ul class="list-unstyled components mb-5">
            <li class="<?= $this->activeController === 'home' ? 'active' : ''; ?>">
                <a href="/">Home</a>
            </li>
            <li class="<?= $this->activeController === 'produtos' ? 'active' : ''; ?>">
                <a
                    class="dropdown-toggle"
                    data-bs-toggle="collapse"
                    href="#produtosSubMenu"
                    role="button"
                    aria-expanded="<?= $this->activeController === 'produtos' ? 'true' : 'false'; ?>"
                    aria-controls="produtosSubMenu"
                >
                    Produtos
                </a>
                <ul
                    class="collapse list-unstyled <?= $this->activeController === 'produtos' ? 'show' : ''; ?>"
                    id="produtosSubMenu"
                >
                    <li class="dropdown-item">
                        <a href="/produtos">Lista</a>
                    </li>
                    <li class="dropdown-item">
                        <a href="/produtos/cadastrar">Cadastrar</a>
                    </li>
                </ul>
            </li>
            <li class="<?= $this->activeController === 'categorias' ? 'active' : ''; ?>">
                <a
                    class="dropdown-toggle"
                    data-bs-toggle="collapse"
                    href="#categoriesSubMenu"
                    role="button"
                    aria-expanded="<?= $this->activeController === 'categorias' ? 'true' : 'false'; ?>"
                    aria-controls="categoriesSubMenu"
                >
                    Categorias
                </a>
                <ul class="collapse list-unstyled <?= $this->activeController === 'categorias' ? 'show' : ''; ?>"
                    id="categoriesSubMenu"
                >
                    <li class="dropdown-item">
                        <a href="/categorias">Lista</a>
                    </li>
                    <li class="dropdown-item">
                        <a href="/categorias/cadastrar">Cadastrar</a>
                    </li>
                </ul>
            </li>
        </ul>

        <div class="footer">
            <p>
                Copyright &copy; All rights reserved
            </p>
        </div>

    </div>
</nav>