<nav id="sidebar">
    <div class="p-4 pt-5">
        <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(assets/images/logo.jpg);"></a>
        <ul class="list-unstyled components mb-5">
            <li class="active">
                <a href="/">Home</a>
            </li>
            <li>
                <a href="#produtosSubMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Produtos</a>
                <ul class="collapse list-unstyled" id="produtosSubMenu">
                    <li>
                        <a href="/produtos">Lista</a>
                    </li>
                    <li>
                        <a href="/produtos/cadastrar">Cadastrar</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#categoriesSubMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Categorias</a>
                <ul class="collapse list-unstyled" id="categoriesSubMenu">
                    <li>
                        <a href="/categorias">Lista</a>
                    </li>
                    <li>
                        <a href="/categorias/registrar">Cadastrar</a>
                    </li>
                </ul>
            </li>
        </ul>

        <div class="footer">
            <p>
                Copyright &copy; All rights reserved
            </p>
        </div>

    </div>
</nav>