<form action="/produtos/<?= strtolower($action); ?>" method="post">
    <div class="form-group">
        <label for="name">Produto</label>
        <input id="name" name="name" type="text" class="form-control" value="<?= $product->name ?? null; ?>">
    </div>
    <div class="form-group">
        <label for="sku">SKU</label>
        <input id="sku" name="sku" type="text" class="form-control" value="<?= $product->sku ?? null; ?>">
    </div>
    <div class="form-group">
        <label for="price">Preço</label>
        <input id="price" name="price" type="text" class="form-control price" value="<?= $product->price ?? null; ?>">
    </div>
    <div class="form-group">
        <label for="quantity">Quantidade</label>
        <input id="quantity" name="quantity" type="text" class="form-control numeric" value="<?= $product->quantity ?? null; ?>">
    </div>
    <div class="form-group">
        <label for="quantity">Categorias</label>
        <select id="categories" name="categories[]" multiple class="form-control">
            <?php if (!empty($categories)) : ?>
                <?php foreach ($categories as $category) : ?>
                    <option value="<?= $category->id; ?>"
                        <?= (
                                !empty($product->categories)
                                && in_array($category->id, $product->categories)
                            ) ? 'selected' : null; ?>
                    ><?= $category->name; ?></option>
                <?php endforeach; ?>
            <?php else : ?>
                <option value="-1">Nenhuma categoria foi cadastrada.</option>
            <?php endif; ?>
        </select>
    </div>
    <button class="btn btn-primary btn-sm btn-block p-2 float-right"><?= $action; ?></button>
</form>

<script>
    $(document).ready(() => {
        $('.price').mask("#.##0,00", {
            reverse: true
        });
        $('.numeric').mask('YYYYYY', {
            'translation': {
                Y: {
                    pattern: /[0-9]/
                }
            }
        });
    });
</script>