<form action="/produtos/<?= strtolower($action); ?>" method="post">
    <div class="form-group">
        <label for="name">Produto</label>
        <input id="name" name="name" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label for="sku">SKU</label>
        <input id="sku" name="sku" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label for="price">Preço</label>
        <input id="price" name="price" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label for="quantity">Quantidade</label>
        <input id="quantity" name="quantity" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label for="quantity">Categorias</label>
        <select id="categories" name="categories[]" multiple class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <button class="btn btn-primary btn-sm btn-block p-2 float-right"><?= $action; ?></button>
</form>